### ISSUE TITLE
Cloudflare 

### ISSUE THREAD

**Issue by cihanerr** [NaiboWang/EasySpider#250]
I appreciate what you have done recently. 
It is a great job however I need an English source / help to figure Cloudflare out.

I could not make it by watching the Chinese video. 

anyone can help?

**Comment by NaiboWang** [comment]
Sorry, Cloudflare is unsupported now since it updates very quickly and our dependencies undetected-chromedriver cannot update as fast as they can and I also don't have the energy to maintain this complicated function.  Therefore, the "Support for Cloudflare" feature has been removed from the official website until further update.
