### ISSUE TITLE
运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据

### ISSUE THREAD

**Issue by famemost** [NaiboWang/EasySpider#413]
![微信截图_20240603234057](https://github.com/NaiboWang/EasySpider/assets/95706039/2d5f4b80-111d-412c-b34b-714c28459681)

**Comment by Gotsumori** [comment]
只能创建项目 不能执行任务 mac也只能用命令打开 然后就是报错如上 面 同样的问题重新下载包 也不能解决

**Comment by NaiboWang** [comment]
把你的截图发过来我看看，要自己创建一个新任务，然后执行这个新任务。

**Comment by famemost** [comment]
> 只能创建项目 不能执行任务 mac也只能用命令打开 然后就是报错如上 面 同样的问题重新下载包 也不能解决

**Comment by famemost** [comment]
> 只能创建项目 不能执行任务 mac也只能用命令打开 然后就是报错如上 面 同样的问题重新下载包 也不能解决

我也是只能命令执行

**Comment by famemost** [comment]
> 把你的截图发过来我看看，要自己创建一个新任务，然后执行这个新任务。
目前来说是正常了，可能是我之前电脑设置了代理的原因

**Comment by Gotsumori** [comment]
我是创建的简单项目 &nbsp;就是Windows很好用 &nbsp;mac就不能直接打开 并且 需要命令执行 任务也完成不了 提示浏览器异常关闭&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Naibo Wang ***@***.***&gt;
发送时间: 2024年6月5日 21:15
收件人: NaiboWang/EasySpider ***@***.***&gt;
抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413)





 
把你的截图发过来我看看，要自己创建一个新任务，然后执行这个新任务。

**Comment by NaiboWang** [comment]
> 我是创建的简单项目 &nbsp;就是Windows很好用 &nbsp;mac就不能直接打开 并且 需要命令执行 任务也完成不了 提示浏览器异常关闭&nbsp; 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Naibo Wang ***@***.***&gt; 发送时间: 2024年6月5日 21:15 收件人: NaiboWang/EasySpider ***@***.***&gt; 抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413) 把你的截图发过来我看看，要自己创建一个新任务，然后执行这个新任务。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

MacOS本来就只能命令执行，可以去看看MACOS的教学视频，至于运行不了，需要你截图我才能定位问题。

**Comment by Gotsumori** [comment]
能不能说具体一点 怎么解决额



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: famemost ***@***.***&gt;
发送时间: 2024年6月5日 21:24
收件人: NaiboWang/EasySpider ***@***.***&gt;
抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413)





  
把你的截图发过来我看看，要自己创建一个新任务，然后执行这个新任务。
 目前来说是正常了，可能是我之前电脑设置了代理的原因

**Comment by Gotsumori** [comment]
是不是执行一次命令 以后就不用执行了 &nbsp;我是每次都执行 &nbsp; &nbsp;并且浏览器老是崩溃
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Naibo Wang ***@***.***&gt;
发送时间: 2024年6月5日 21:30
收件人: NaiboWang/EasySpider ***@***.***&gt;
抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413)





  
我是创建的简单项目 &nbsp;就是Windows很好用 &nbsp;mac就不能直接打开 并且 需要命令执行 任务也完成不了 提示浏览器异常关闭&nbsp; 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Naibo Wang @.&gt; 发送时间: 2024年6月5日 21:15 收件人: NaiboWang/EasySpider @.&gt; 抄送: Gotsumori @.&gt;, Comment @.&gt; 主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413) 把你的截图发过来我看看，要自己创建一个新任务，然后执行这个新任务。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
MacOS本来就只能命令执行，可以去看看MACOS的教学视频，至于运行不了，需要你截图我才能定位问题。

**Comment by NaiboWang** [comment]
> 是不是执行一次命令 以后就不用执行了 &nbsp;我是每次都执行 &nbsp; &nbsp;并且浏览器老是崩溃 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Naibo Wang ***@***.***&gt; 发送时间: 2024年6月5日 21:30 收件人: NaiboWang/EasySpider ***@***.***&gt; 抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413) 我是创建的简单项目 &nbsp;就是Windows很好用 &nbsp;mac就不能直接打开 并且 需要命令执行 任务也完成不了 提示浏览器异常关闭&nbsp; 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Naibo Wang @.&gt; 发送时间: 2024年6月5日 21:15 收件人: NaiboWang/EasySpider @.&gt; 抄送: Gotsumori @.&gt;, Comment @.&gt; 主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413) 把你的截图发过来我看看，要自己创建一个新任务，然后执行这个新任务。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; MacOS本来就只能命令执行，可以去看看MACOS的教学视频，至于运行不了，需要你截图我才能定位问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请你把截图发来

**Comment by Gotsumori** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Naibo Wang ***@***.***&gt;
发送时间: 2024年6月5日 21:37
收件人: NaiboWang/EasySpider ***@***.***&gt;
抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413)





  
是不是执行一次命令 以后就不用执行了 &nbsp;我是每次都执行 &nbsp; &nbsp;并且浏览器老是崩溃 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Naibo Wang @.&gt; 发送时间: 2024年6月5日 21:30 收件人: NaiboWang/EasySpider @.&gt; 抄送: Gotsumori @.&gt;, Comment @.&gt; 主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413) 我是创建的简单项目 &nbsp;就是Windows很好用 &nbsp;mac就不能直接打开 并且 需要命令执行 任务也完成不了 提示浏览器异常关闭&nbsp; 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Naibo Wang @.&gt; 发送时间: 2024年6月5日 21:15 收件人: NaiboWang/EasySpider @.&gt; 抄送: Gotsumori @.&gt;, Comment @.&gt; 主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413) 把你的截图发过来我看看，要自己创建一个新任务，然后执行这个新任务。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; MacOS本来就只能命令执行，可以去看看MACOS的教学视频，至于运行不了，需要你截图我才能定位问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
请你把截图发来

**Comment by Gotsumori** [comment]
<img width="651" alt="截屏2024-06-05 21 45 55" src="https://github.com/NaiboWang/EasySpider/assets/101912613/e896503a-9889-4db6-addd-3b7c8eb13791">
![Uploading 截屏2024-06-05 21.44.44.png…]()

**Comment by Gotsumori** [comment]
<img width="651" alt="截屏2024-06-05 21 45 55" src="https://github.com/NaiboWang/EasySpider/assets/101912613/7df78fa4-c46e-44eb-a669-0461ef03992c">
<img width="476" alt="截屏2024-06-05 21 44 44" src="https://github.com/NaiboWang/EasySpider/assets/101912613/58a2acbb-893a-4aa0-bb4b-fc9cd0312e4d">

**Comment by NaiboWang** [comment]
你的Mac是Arm芯片还是Intel芯片？你下载的是哪个版本的EasySpider？MacOS操作系统版本是什么？

**Comment by Gotsumori** [comment]
M2 版本下载的arm版的 操作系统是sonoma14.5



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Naibo Wang ***@***.***&gt;
发送时间: 2024年6月5日 22:17
收件人: NaiboWang/EasySpider ***@***.***&gt;
抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413)





 
你的Mac是Arm芯片还是Intel芯片？你下载的是哪个版本的EasySpider？MacOS操作系统版本是什么？

**Comment by NaiboWang** [comment]
把整个命令行截全

**Comment by Gotsumori** [comment]
![Uploading 截屏2024-06-05 22.24.44.png…]()

**Comment by NaiboWang** [comment]
这图片没传好，看不到。

**Comment by Gotsumori** [comment]
邮件发送了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Naibo Wang ***@***.***&gt;
发送时间: 2024年6月5日 22:21
收件人: NaiboWang/EasySpider ***@***.***&gt;
抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413)





 
把整个命令行截全

**Comment by NaiboWang** [comment]
我看不到

**Comment by Gotsumori** [comment]
网络服务器太卡 &nbsp;经常打不开



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Naibo Wang ***@***.***&gt;
发送时间: 2024年6月5日 22:29
收件人: NaiboWang/EasySpider ***@***.***&gt;
抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413)





 
这图片没传好，看不到。

**Comment by Gotsumori** [comment]
![Uploading 截屏2024-06-05 22.24.44.png…]()

**Comment by NaiboWang** [comment]
截图不了你直接把这个命令行复制一遍发到这吧

**Comment by Gotsumori** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Naibo Wang ***@***.***&gt;
发送时间: 2024年6月5日 22:34
收件人: NaiboWang/EasySpider ***@***.***&gt;
抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413)





 
截图不了你直接把这个命令行复制一遍发到这吧

**Comment by Gotsumori** [comment]
https://66img.cc/images/2024/06/05/2024-06-05-22.24.44.png

**Comment by NaiboWang** [comment]
看到了，但这个问题我解决不了，因为不知道什么原因引起的，我自己没有碰到过类似问题，可以试试退出所有的Chrome，然后重启电脑再试试。

**Comment by Gotsumori** [comment]
好的 &nbsp;辛苦 辛苦 &nbsp;等以后遇到多了再说吧 先用 Windows 体验也不错



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Naibo Wang ***@***.***&gt;
发送时间: 2024年6月5日 22:59
收件人: NaiboWang/EasySpider ***@***.***&gt;
抄送: Gotsumori ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [NaiboWang/EasySpider] 运行一直报同一个错误，运行文件夹中自带的爬虫脚本都是报一样错误，浏览器也没有起来，没有产生数据 (Issue #413)





 
看到了，但这个问题我解决不了，因为不知道什么原因引起的，我自己没有碰到过类似问题，可以试试退出所有的Chrome，然后重启电脑再试试。
